#!/bin/bash

FILENAME=`git log -1 HEAD --pretty=oneline`
FILENAME=${FILENAME:1:24}.jpg

uvccapture -o${HOME}/Pictures/${FILENAME} -x1280 -y960 

write_repo_as_label(){

repo=$(git remote -v | cut -d' ' -f1 | cut -f2 | cut -d':' -f2 | head -n 1)
# $repo
convert ${HOME}/Pictures/${FILENAME} -pointsize 20 -draw "gravity south fill black  text 0,12 '${repo}' fill white  text 1,11 '${repo}' " \
${HOME}/Pictures/{$FILENAME}
}

write_repo_as_label
